platform :ios, '11.0'

target 'nkoodiVendor' do
  
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'QRCode'
  pod 'IQKeyboardManagerSwift'

  target 'nkoodiVendorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nkoodiVendorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
